.bintray.template
Makefile

- Windows distribution was missing a ';' to break the mv command from the 
artifact name. 
- Travis bintray upload does not place the files under the package directory 
by default, so it needs to be added to the upload pattern.
- Fix checks to detect latest release or not.

Fix bintray release scripts

---

e2e/e2e_test.go
e2e/ospreytest/fixtures.go
server/osprey/server.go
server/web/server.go

Osprey will now start when dex is not running/unavailable/unreachable.
Also introduced `/healthz` endpoint for osprey server which can be used
as a liveness probe in the deployment.
Migrating over from https://github.com/sky-uk/core-infrastructure/pull/1896

Osprey can start when dex is unavailable

---

CHANGELOG.md
README.md
client/config.go
cmd/login.go
cmd/serve.go
common/web/client.go
e2e/e2e_test.go
e2e/ospreytest/fixtures.go
e2e/ospreytest/server.go

This allows a user to paste in base64-encoded CA certificates, similar to kubeconfig files. With this enhancement, users can freely share their Osprey config files within their organization without worrying about file paths that can change between machines.

Add support for loading CA data from base64

---

client/kubeconfig/config.go
e2e/login_test.go

Prevents osprey from erasing context config
e.g. default namespace
#17

Preserve context config on user login

---

CHANGELOG.md
client/config_snapshot.go
e2e/targets_test.go

Fixes `osprey config targets` displaying a target multiple times if the
target belongs to multiple groups.
Related to https://github.com/sky-uk/osprey/issues/9

List target only once if in multiple groups

---

.bintray.latest.template
.travis.yml
CHANGELOG.md
Makefile

Treat `latest` as a version in bintray, and deploy the current version
and the latest version artifacts separately.
The bintray deploy task originally created included the latest artifacts
as part of the bintray deploy for a specific version.
Because of this, subsequent releases failed to update the artifacts, as
they were tied to a specific version, e.g.
```
Bintray Upload] Bintray response: 409 Conflict. Unable to upload files:
An artifact with the path '[...]' already exists under another version.
```

Fix latest release publishing

---

CHANGELOG.md
Makefile

It was missing a `\` in one of the shell lines

Fix prepare-release-bintray make target

---

Makefile

- Use an absolute path to the template.
- Add missing `;` to split `sed` and `echo` commands for latest.

Fix latest template generation

---

client/oidc/oidc.go

This is a small convenience to remove the need to manually close the login window.
800ms chosen scientifically as not too slow and not too fast.
This is a follow up to https://github.com/sky-uk/osprey/pull/52.

Close the browser window automatically after login

---

client/oidc/oidc.go

window.close() seems to work okay on Chrome for refreshing a session.

Use window.close() so it doesn't make Firefox unhappy

---

client/config.go
cmd/config.go
cmd/user.go
go.mod
go.sum

On Linux systems, config should go into `~/.config`, not in the top
level home directory. This changes Osprey to support the XDG config
directory. It will also support the older `~/.osprey` location.

Conform to XDG standards for configuration

---

CHANGELOG.md
README.md
client/azure.go
client/config.go
client/credentials.go
client/kubeconfig/config.go
client/oidc/device.go
client/oidc/oidc.go
client/oidc/util.go
client/osprey.go
client/target.go
cmd/auth.go
common/ioutil.go
common/pb/util.go
common/web/client.go
e2e/apiservertest/server.go
e2e/clitest/async_command.go
e2e/dextest/server.go
e2e/e2e_suite_test.go
e2e/ldaptest/server.go
e2e/login_test.go
e2e/logout_test.go
e2e/oidc_login_test.go
e2e/oidctest/server.go
e2e/ospreytest/fixtures.go
e2e/ospreytest/server.go
e2e/targets_test.go
e2e/user_test.go
server/osprey/server.go
server/web/server.go

Add an optional `api-server:` field to the Osprey client config file. If this is used, the API Server CA certificate will be fetched directly from the API Server rather than relying on a deployment of Osprey server
to serve the CA.
To use this, the cluster must have a ConfigMap called `kube-root-ca.crt` in the `kube-public` namespace that is accessible by `system:anonymous` users. The following should work:
```
curl -k https://APISERVER/api/v1/namespaces/kube-public/configmaps/kube-root-ca.crt
```
This ConfigMap is created automatically as part of the `RootCAConfigMap` feature gate introduced in Kubernetes 1.13, which became enabled by default in v1.20 ([changelog](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.20.md#introducing-rootcaconfigmap)).
Note to …

Allow osprey client to read CA cert directly from API server

---

.travis.yml

Bintray has been discontinued and hence master builds are failing. See #64 that explores other binary distribution options.

Stop releasing to Bintray

---

.goreleaser.yml
.travis.yml
Makefile

Goreleaser will compile binaries, package them and upload as a release draft go GitHub when there is a tagged build in Travis.
Fixes #62 and #64.

Add goreleaser

---

CHANGELOG.md
README.md
client/azure.go
client/config.go
client/osprey.go
client/target.go
e2e/apiservertest/server.go
e2e/e2e_suite_test.go
e2e/login_test.go
e2e/logout_test.go
e2e/oidc_login_test.go
e2e/ospreytest/server.go
e2e/targets_test.go
e2e/user_test.go

This allows osprey client to fetch the API server URL from the `kube-public`/`ClientConfig` resource. This is created when the [OIDC Identity Service](https://cloud.google.com/kubernetes-engine/docs/how-to/oidc) is enabled in GKE. This is an Envoy proxy that passes requests through the OIDC service. The API server CA cert is also fetched from the ClientConfig resource.
It seems like a chicken-and-egg situation that the API server URL is retrieved from the API server, but typically the public URL would be used in order to fetch the internal OIDC proxy URL.
Note: when `use-gke-clientconfig: true` is specified `api-server` is also required, to know from where to retrieve the ClientConfig.
```yaml
providers:
azure:
...
targets:
sandbox2.gcp:
api-server: https://34.79.49.27 …
```

Fetch API server URL from GKE OIDC ClientConfig

---

client/azure.go
client/oidc/device.go
client/oidc/oidc.go
e2e/oidc_login_test.go
e2e/oidctest/server.go

For sky/core-aws#2448
Updates Osprey to use V2.0 of the `/.well-known/openid-configuration` API.  This in turn make's Osprey use `/oauth2/v2.0/authorize` endpoint returned from the open-id config.  
Version 2.0 handles situations where users have large numbers of groups in Azure.  The authorisation then starts to return "distributed claims" instead of just the groups directly due to the number of them. Instead of the groups list, a URL is provided, from where the list can be fetched (see [Groups overage claim](https://docs.microsoft.com/en-us/azure/active-directory/develop/id-tokens#groups-overage-claim)).
Once updated to v2.0 the kubernetes API servers are already setup to handle this.

Azure OIDC V2.0 authorisation updates

---

.goreleaser.yml
Makefile
client/azure.go
client/config.go
client/credentials.go
client/kubeconfig/config.go
client/osprey.go
cmd/auth.go
cmd/cluster-info.go
cmd/login.go
cmd/logout.go
cmd/targets.go
cmd/user.go
e2e/dextest/server.go
e2e/e2e_suite_test.go
e2e/ldaptest/server.go
e2e/login_test.go
e2e/logout_test.go
e2e/oidc_login_test.go
e2e/oidctest/server.go
e2e/ospreytest/fixtures.go
e2e/ospreytest/server.go
e2e/server_test.go
e2e/shared_output_test.go
e2e/targets_test.go
e2e/user_test.go
go.mod
main.go
server/osprey/server.go
server/web/server.go

For #77 
This resolve the go install issue and honours go package structure correctly now. Essentially when the git versioning moved to v2.X.X we should have introduced /v2 into the module name.  There are various ways to package it up when this happens including having all of the V1 code at root and then having a copy go into a v2 subfolder and development continue in there, with the v1 root being for backwards compatibility.
However, I believe we only want one version of the code in our master. As such, this PR moves the module entirely to v2.  Thus, go install now works as expected using this:
```
go install github.com/sky-uk/osprey/v2@v2.8.0
```
Indeed you can even use @latest and it will find the current v2.8.0 version:
```
go install github.com/sky-uk/osprey/v2@latest
```
The …

Update imports for v2 compatibility

---

.travis.yml
README.md

Main change:
* Since #81 the Windows binary will read the system's CA bundle, hence removing "mandatory for Windows" from the README: 
```diff
@@ -230,38 +231,34 @@ The client uses a yaml configuration file. It's recommended location is:
providers:
osprey:
-    # Mandatory for windows, optional for unix systems.
-    # CA cert to use for HTTPS connections to osprey.
-    # Uses system's CA certs if absent (only in unix systems).
+    # CA cert to use for HTTPS connections to Osprey.
+    # Uses system's CA certs if absent.
```
Other tidy-ups:
* Remove `GO111MODULE=on` because since Go 1.16 it's the default https://github.com/golang/go/issues/41330
* Remove flag that skips releasing to Bintray, since we stopped releasing there in #70 
* Fixed some capitalisation and typos in README

Update README for Windows certs + tidy-ups

---

CHANGELOG.md
README.md
client/azure.go
client/config.go
client/group.go
client/osprey.go
client/target.go
cmd/auth.go
common/web/client.go
e2e/ospreytest/fixtures.go

This change makes the TLS verification choice explicit in the configuration rather than relying on whether the CA's are present or not (logic added as part of https://github.com/sky-uk/osprey/pull/69).

Add ability to skip TLS when connecting to server

---

.goreleaser.yml

goreleaser now errors because of the deprecated `archives.replacements` config: https://goreleaser.com/deprecations/#archivesreplacements
the original config can just be deleted since its only purpose is being cute about the name of the tarball.

fix the goreleaser build

---

README.md
e2e/Dockerfile.localtest
e2e/e2e_suite_test.go

- Local e2e tests rely on having an ldap setup which is incredibly difficult to setup locally as the versions keep changing and with it some of the configurations. Hence, keeping the local dockerfile aligned with the os used on travis node will keep local development aligned with CI builds.
- Changes to os versions on travis node can then be upgraded organically

Add Dockerfile for running e2e tests
